services:
  lb:
    image: nginx:alpine
    ports: ["80:80"]
    volumes: ["./nginx.conf:/etc/nginx/nginx.conf:ro"]
    restart: always

  web_a:
    image: nginx:alpine
    volumes: ["./sites/a:/usr/share/nginx/html:ro"]

  web_b:
    image: nginx:alpine
    volumes: ["./sites/b:/usr/share/nginx/html:ro"]

  web_c:
    image: nginx:alpine
    volumes: ["./sites/c:/usr/share/nginx/html:ro"]
